package model;

import enums.Role;

import java.sql.ResultSet;
import java.sql.SQLException;

public class Movie {
    private int movieId; // Assuming this is auto-generated by the database
    private String title;
    private String genre;
    private Integer releaseYear;
    private Boolean isAvailable;

    // Constructors
    public Movie() {
    }

    // Additional constructor, getters, and setters as needed
    public Movie(String title, String genre, int releaseYear, boolean isAvailable) {
        this.title = title;
        this.genre = genre;
        this.releaseYear = releaseYear;
        this.isAvailable = isAvailable;
    }
    public Movie(int movieId, String title, String genre, int releaseYear, boolean isAvailable) {
        this.movieId = movieId;
        this.title = title;
        this.genre = genre;
        this.releaseYear = releaseYear;
        this.isAvailable = isAvailable;
    }


    public Movie(ResultSet rs) throws SQLException {
        // Assuming column names in the ResultSet match the field names
        this.movieId = rs.getInt("movieId");
        this.title = rs.getString("title");
        this.genre = rs.getString("genre");
        this.releaseYear = rs.getInt("releaseYear");
        this.isAvailable = rs.getBoolean("isAvailable");
    }

    // Getters and setters
    public int getMovieId() { return movieId; }

    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }
    public Integer getReleaseYear() { return releaseYear; }

    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }
    public String getTitle() { return title; }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGenre() { return genre; }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public Boolean isAvailable() { return isAvailable; }

    public void setAvailable(Boolean available) {
        this.isAvailable = available;
    }



}
