package model;

public class Movie {
    private int movieId; // Assuming this is auto-generated by the database
    private String title;
    private String genre;
    private Integer releaseYear;
    private Boolean isAvailable;

    // Constructors
    public Movie() {
    }

    // Additional constructor, getters, and setters as needed
    public Movie(String title, String genre, int releaseYear, boolean isAvailable) {
        this.title = title;
        this.genre = genre;
        this.releaseYear = releaseYear;
        this.isAvailable = isAvailable;
    }

    // Getters and setters
    public int getMovieId() { return movieId; }

    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }
    public Integer getReleaseYear() { return releaseYear; }

    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }
    public String getTitle() { return title; }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGenre() { return genre; }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public Boolean isAvailable() { return isAvailable; }

    public void setAvailable(Boolean available) {
        this.isAvailable = available;
    }



}
